Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.define "shellql"
  config.vm.hostname = 'shellql'

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "setup.yml"
      ansible.become = true
    end
end


